// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3t9JK8Q_LQ6xq9T8KXIXQR66DmdwPTUU',
    appId: '1:63268418335:web:797366837f83d46a59b62a',
    messagingSenderId: '63268418335',
    projectId: 'trai-ui',
    authDomain: 'trai-ui.firebaseapp.com',
    storageBucket: 'trai-ui.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJtYz-8IHC7-UerPjJaUPiLykaCVOvdEc',
    appId: '1:63268418335:android:5a2d4921dde4914159b62a',
    messagingSenderId: '63268418335',
    projectId: 'trai-ui',
    storageBucket: 'trai-ui.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyZA32xyp3vjGBTY2yvQhKbf3k9YAmTnU',
    appId: '1:63268418335:ios:fdafcd821e43738559b62a',
    messagingSenderId: '63268418335',
    projectId: 'trai-ui',
    storageBucket: 'trai-ui.firebasestorage.app',
    androidClientId: '63268418335-vvsbeqdfp9njebmekrdamcpddqnbgu21.apps.googleusercontent.com',
    iosClientId: '63268418335-ro81ae649jc86dv57ia4onn40ulp11ea.apps.googleusercontent.com',
    iosBundleId: 'com.example.newTraiProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyZA32xyp3vjGBTY2yvQhKbf3k9YAmTnU',
    appId: '1:63268418335:ios:fdafcd821e43738559b62a',
    messagingSenderId: '63268418335',
    projectId: 'trai-ui',
    storageBucket: 'trai-ui.firebasestorage.app',
    androidClientId: '63268418335-vvsbeqdfp9njebmekrdamcpddqnbgu21.apps.googleusercontent.com',
    iosClientId: '63268418335-ro81ae649jc86dv57ia4onn40ulp11ea.apps.googleusercontent.com',
    iosBundleId: 'com.example.newTraiProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3t9JK8Q_LQ6xq9T8KXIXQR66DmdwPTUU',
    appId: '1:63268418335:web:5a6325f5c436384759b62a',
    messagingSenderId: '63268418335',
    projectId: 'trai-ui',
    authDomain: 'trai-ui.firebaseapp.com',
    storageBucket: 'trai-ui.firebasestorage.app',
  );
}
